### ISSUE TITLE
the ltm package in R

### ISSUE THREAD

**Issue by jwdcscorp** [drizopoulos/ltm#21]
Hello there.

Hope this message finds you well.

We noticed two minor issues in the ltm package in R. We are a group of I/O psychologists who use the package all the time and overall are very happy with it!

The first issue is with the naming convention for some functions in the documentation. We hand calculated biserial and point biserial correlations using our own data and then compared the output against the output from the descript() function. It looks like the ltm package produces point biserials (not biserials). The documentation for the ltm package is a little confusing because it keeps referring to the function biserial.cor() and the output from the descript() functions as biserials when in fact it is point biserials. As you know, the two correlations are different and therefore, we are reaching out with a friendly request to (1) update the documentation for the ltm package to clarify that the ITCs are point biserials and (2) to update the name of the biserial.cor() function to perhaps pbiserial.cor().

The second issue is with the rasch() function in the same R package. We used our own data and the mirt() package to verify the ltm's output for the rasch() function and we discovered that the R spits out the 1PL model estimates, not the Rasch model estimates. So, we are reaching out with another friendly request to update the name of the function in the ltm package from rasch() to perhaps onePL() to ensure the congruency between the function name and the output it creates. 

Other than that, your package has been instrumental to our work. Thank you so much for putting it together!

**Comment by drizopoulos** [comment]
Thanks! Regarding your points, 

- The documentation of `biserial.cor()` clearly states that this is the point biserial correlation coefficient. Also, the relevant part in the output of `descript()` also clearly states that point biserials are given. Because of backward compatibility issues, I'm not willing to change the name of this function because it will break the code of other users.
- Likewise the documentation of `rasch()` clearly states what model is fitted. The Rasch model is also fitted by this function using the `constraint` argument. For the same reasons, I'm unwilling to change the function's name because it will break a lot of code.
